### ISSUE TITLE
incorrect table name `notificatoin_users`

### ISSUE THREAD

**Issue by zzhovo** [NovemBit/wp-task-manager#16]
https://github.com/NovemBit/wp-task-manager/blob/48a123f1024a9896743b6eed1ac7e5c9ffee52ec/data-provider/class-btm-notification-dao.php#L45

**Comment by zzhovo** [comment]
the table name also should be `notification` instead of `notificatoin`

**Comment by grogou** [comment]
fixed but I think about live sites where this table name ''notificatoin''
