### ISSUE TITLE
incorrect $wpdb->prepare usage

### ISSUE THREAD

**Issue by zzhovo** [NovemBit/wp-task-manager#17]
https://github.com/NovemBit/wp-task-manager/blob/48a123f1024a9896743b6eed1ac7e5c9ffee52ec/data-provider/view/class-btm-task-run-log-view-dao.php#L132

**Comment by zzhovo** [comment]
https://github.com/NovemBit/wp-task-manager/blob/48a123f1024a9896743b6eed1ac7e5c9ffee52ec/data-provider/view/class-btm-task-bulk-argument-view-dao.php#L49

**Comment by zzhovo** [comment]
https://github.com/NovemBit/wp-task-manager/blob/48a123f1024a9896743b6eed1ac7e5c9ffee52ec/data-provider/class-btm-task-dao.php#L424

**Comment by grogou** [comment]
fixed
