### ISSUE TITLE
Filter prefix hard-coded

### ISSUE THREAD

**Issue by zzhovo** [NovemBit/wp-task-manager#23]
https://github.com/NovemBit/wp-task-manager/blob/4c9cd31f1e8ee4332fc5fa15acf85f463bceb0b9/core/class-btm-task-delete-old-entities-manager.php#L30

filter name prefix should be get from the plugin options class

**Comment by grogou** [comment]
I think it's ok for this case or I can add global prefix function in plugin options?do it?

**Comment by grogou** [comment]
fixed
